version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=ricardo
      - POSTGRES_PASSWORD=asdasd123
    ports:
      - 5433:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=ricardo@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80


